with Interfaces; use Interfaces;

package xgraph is
   type ViewPortType is
      record X1, Y1, X2, Y2 : Integer;
         Clip : Boolean;
   end record;
   --  external name 'ScreenHeight';
   --  external name 'ScreenWidth';
   --  cdecl; external name 'crtWindow';
   procedure InitGraph (GraphDriver, GraphModus : in out Integer;
                        PathToDriver : String);
   procedure CloseGraph;
   procedure SetColor (Color : Integer_32);
   procedure SetFillStyle (Pattern, Color : Integer_32);
   procedure SetLineStyle (LineStyle, Pattern, Width : Integer_32);
   procedure Line (X1, Y1, X2, Y2 : Integer_32);
   procedure PutPixel (X, Y : Integer_32; Color : Integer_32);
   procedure Bar (X1, Y1, X2, Y2 : Integer_32);
   procedure Rectangle (X1, Y1, X2, Y2 : Integer_32);
   procedure Arc (X, Y : Integer_32; start, stop, radius : Integer_32);
   procedure FillEllipse (X, Y : Integer_32; Xradius, YRadius : Integer_32);
   procedure Circle (X, Y : Integer_32; Radius : Integer_32);
   procedure FloodFill (X, Y : Integer_32; BorderColor : Integer_32);
   procedure SetTextJustify (Horizontal, Vertical : Integer_32);
   procedure OutTextXY (X, Y : Integer; TextString : String);
   procedure SetViewPort (X1, Y1, X2, Y2 : Integer_32; Clip : Boolean);
   function  GetBkColor return Integer_32;
   procedure SetBkColor (Color : Integer_32);
   function  GraphErrorMsg (ErrorCode : Integer_32) return String;
   function  GraphResult return Integer_32;
   procedure GetBox (bn, x, y, width, height : Integer_32);
   procedure PutBox (bn, x, y, width, height : Integer_32);
   procedure init_x;

   ScreenHeight : Integer;
   ScreenWidth  : Integer;

   SOLIDFILL    : constant := 0;
   lefttext     : constant := 0;
   centertext   : constant := 1;
   righttext    : constant := 2;
   userbitln    : constant := 4;
   normwidth    : constant := 1;
   solidln      : constant := 0;
   VGA          : constant := 0;
   EGA          : constant := 1;
   GROK         : constant := 0;
   Black        : constant := 0;
   Blue         : constant := 1;
   Green        : constant := 2;
   Cyan         : constant := 3;
   Red          : constant := 4;
   Magenta      : constant := 5;
   Brown        : constant := 6;
   LightGray    : constant := 7;
   DarkGray     : constant := 8;
   LightBlue    : constant := 9;
   LightGreen   : constant := 10;
   LightCyan    : constant := 11;
   LightRed     : constant := 12;
   LightMagenta : constant := 13;
   Yellow       : constant := 14;
   White        : constant := 15;
   co80         : constant := 3;
   WindMax      : Unsigned_16 := 16#184f#;
   LastMode     : Unsigned_16 := 3;
   DirectVideo  : Boolean := False;

   procedure Window (X1, Y1, X2, Y2 : Integer_32);
   procedure GotoXY (X : Integer_32; Y : Integer_32);
   procedure Sound (hz : Integer_32);
   procedure P2Ada_no_keyword_Delay (DTime : Integer_32);
   procedure NoSound;
   function  KeyPressed return Boolean;
   function  ReadKey return Character;
   procedure TextMode (Mode : Integer_32);
   procedure TextColor (CL : Integer_32);
   procedure TextBackground (CL : Integer_32);
   procedure ClrScr;
   function GetTimerTicks return Integer;
end xgraph;
